### ISSUE TITLE
wikiloves.py relies on not provided db.json

### ISSUE THREAD

**Issue by JeanFred** [ptwikis/wikiloves#1]
Hi,

I wanted to have a look at this tool and run it locally. It relies on a `db.json` file that is not provided. Would you happen to have a copy of it ? :)

Thanks!

**Comment by JeanFred** [comment]
Ping? :)

**Comment by danilomac** [comment]
Hi, sorry the delay. You are now a tool maintainer, but everybody who have account in Tool Labs can access the file, it is in `/data/project/wikiloves/wikiloves/db.json`.
